### ISSUE TITLE
By using the memonger, the network could not be finetuned?

### ISSUE THREAD

**Issue by taylover-pei** [dmlc/mxnet-memonger#10]
When I use the memonger,  and I use the function of load_checkpoint(), but in this line
                assert sys.tojson() == network.tojson()
is failed. This means that the structure of the network using the memonger is not match with the pre-trained network. So I do not know what is the reason?

**Comment by 315386775** [comment]
Traceback (most recent call last):
  File "train.py", line 96, in <module>
    net_mem_planned = memonger.search_plan(new_sym, data=dshape)
  File "/home1/mxnet/memonger.py", line 141, in search_plan
    sym = make_mirror_plan(sym, threshold=threshold, plan_info=info, **kwargs)
  File "/home1/mxnet/memonger.py", line 63, in make_mirror_plan
    shape_dict = list(zip(internals.list_outputs(), out_shapes))
TypeError: zip argument #2 must support iteration
